src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>C501_Annual_Income__c</fullName>
        <inlineHelpText>Annual Income for the household - used to calculate Income Level</inlineHelpText>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>C501_Child_Support__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Child Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Earned_Income__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Earned Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Household_Income_Sources__c</fullName>
        <description>Module4</description>
        <label>Household Income Sources</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Income from Employment Only</fullName>
                </value>
                <value>
                    <fullName>Income from Employment and Other Income Source</fullName>
                </value>
                <value>
                    <fullName>Income from Employment, Other Income Source, and Non-Cash Benefits</fullName>
                </value>
                <value>
                    <fullName>Income from Employment and Non-Cash Benefits</fullName>
                </value>
                <value>
                    <fullName>Other Income Source Only</fullName>
                </value>
                <value>
                    <fullName>Other Income Source and Non-Cash Benefits</fullName>
                </value>
                <value>
                    <fullName>No Income</fullName>
                </value>
                <value>
                    <fullName>Non-Cash Benefits Only</fullName>
                </value>
                <value>
                    <fullName>Unknown/Not Reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C501_Household_Size__c</fullName>
        <description>Module4</description>
        <inlineHelpText>Number of people in the household - including those who are not listed as Contacts. Used to calculate HH Income Level and in Module4 reporting.</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>C501_Housing__c</fullName>
        <description>Module4</description>
        <label>Housing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Own</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>Other permanent housing</fullName>
                </value>
                <value>
                    <fullName>Homeless</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Unknown/Not Reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C501_Other_Income__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Other Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Pension__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Pension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Retirement_Income_Social_Security__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Retirement Income - Social Security</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_SNAP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>SNAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Self_Employed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Self Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Service_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Service Id</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>C501_Supplemental_Security_Income__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Supplemental Security Income (SSI)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_TANF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>TANF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Unemployment_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Unemployment Insurance</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/C501_Service_Contact__c.object
<CustomObject>
    <fields>
        <fullName>C501_Contact_Id__c</fullName>
        <description>External Contact Id</description>
        <externalId>true</externalId>
        <label>Contact_Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>C501_Service_Id__c</fullName>
        <description>External Service Id</description>
        <externalId>true</externalId>
        <label>Service Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Service Contact</label>
    <nameField>
        <label>Service Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/C501_Service_Household__c.object
<CustomObject>
    <fields>
        <fullName>C501_Annual_Income__c</fullName>
        <inlineHelpText>Annual Income for the household - used to calculate Income Level</inlineHelpText>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>C501_BillingCity__c</fullName>
        <label>BillingCity</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_BillingPostalCode__c</fullName>
        <label>BillingPostalCode</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_BillingState__c</fullName>
        <label>BillingState</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_BillingStreet__c</fullName>
        <label>BillingStreet</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_Child_Support__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Child Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Earned_Income__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Earned Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Household_Income_Sources__c</fullName>
        <description>Module4</description>
        <label>Household Income Sources</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Income from Employment Only</fullName>
                </value>
                <value>
                    <fullName>Income from Employment and Other Income Source</fullName>
                </value>
                <value>
                    <fullName>Income from Employment, Other Income Source, and Non-Cash Benefits</fullName>
                </value>
                <value>
                    <fullName>Income from Employment and Non-Cash Benefits</fullName>
                </value>
                <value>
                    <fullName>Other Income Source Only</fullName>
                </value>
                <value>
                    <fullName>Other Income Source and Non-Cash Benefits</fullName>
                </value>
                <value>
                    <fullName>No Income</fullName>
                </value>
                <value>
                    <fullName>Non-Cash Benefits Only</fullName>
                </value>
                <value>
                    <fullName>Unknown/Not Reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C501_Household_Size__c</fullName>
        <description>Module4</description>
        <inlineHelpText>Number of people in the household - including those who are not listed as Contacts. Used to calculate HH Income Level and in Module4 reporting.</inlineHelpText>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>C501_Household__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Households</relationshipLabel>
        <relationshipName>Service_Households</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>C501_Housing__c</fullName>
        <description>Module4</description>
        <label>Housing</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Own</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>Other permanent housing</fullName>
                </value>
                <value>
                    <fullName>Homeless</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Unknown/Not Reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C501_Other_Income__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Other Income</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Pension__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Pension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Retirement_Income_Social_Security__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Retirement Income - Social Security</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_SNAP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>SNAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Self_Employed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Self Employed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Service_Id__c</fullName>
        <externalId>true</externalId>
        <label>Service Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>C501_ShippingCity__c</fullName>
        <label>ShippingCity</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_ShippingPostalCode__c</fullName>
        <label>ShippingPostalCode</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_ShippingState__c</fullName>
        <label>ShippingState</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_ShippingStreet__c</fullName>
        <label>ShippingStreet</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C501_Supplemental_Security_Income__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Supplemental Security Income (SSI)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_TANF__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>TANF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>C501_Unemployment_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Module4</description>
        <label>Unemployment Insurance</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Household</label>
    <nameField>
        <label>Service Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>C501_Contact_Id__c</fullName>
        <externalId>true</externalId>
        <label>Contact Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>C501_Service_Id__c</fullName>
        <externalId>true</externalId>
        <label>Service Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/C501_TriggerHelperTest.cls
@isTest
public with sharing class C501_TriggerHelperTest {

	@isTest
	private static void testTriggers() {

		Account hh = new Account (
			Name = 'Account.Name',
			C501_Service_Id__c = 'sh1'
		);
		insert hh;

		Contact c = new Contact(
			LastName = 'Contact.LastName',
			C501_Contact_Id__c = 'sc1',
			C501_Service_Id__c = hh.C501_Service_Id__c,
			AccountId = hh.Id
		);
		insert c;

		C501_Service_Household__c sh = new C501_Service_Household__c(
            Name = 'C501_Service_Household__c.Name',
			C501_Household__c = hh.Id,
			C501_Service_Id__c = hh.C501_Service_Id__c
		);
		insert sh;

		// Call update to execute trigger
		sh.C501_BillingStreet__c = 'C501_BillingStreet__c';
		sh.C501_BillingCity__c = 'C501_BillingCity__c';
		sh.C501_BillingState__c = 'C501_BillingState__c';
		sh.C501_BillingPostalCode__c = '54321';
		sh.C501_ShippingStreet__c = 'C501_ShippingStreet__c';
		sh.C501_ShippingCity__c = 'C501_ShippingCity__c';
		sh.C501_ShippingState__c = 'C501_ShippingState__c';
		sh.C501_ShippingPostalCode__c = '12345';
		sh.C501_SNAP__c = TRUE;
		sh.C501_Other_Income__c = TRUE;
		sh.C501_Earned_Income__c = TRUE;
		sh.C501_Self_Employed__c = TRUE;
		sh.C501_Unemployment_Insurance__c = TRUE;
		sh.C501_Child_Support__c = TRUE;
		sh.C501_Pension__c = TRUE;
		sh.C501_Retirement_Income_Social_Security__c = TRUE;
		sh.C501_Supplemental_Security_Income__c = TRUE;
		sh.C501_TANF__c = TRUE;
		sh.C501_Household_Income_Sources__c = 'Unknown/Not Reported';
		sh.C501_Annual_Income__c = 1000;
		sh.C501_Housing__c = 'Unknown/Not Reported';
		sh.C501_Household_Size__c = 2;
		sh.C501_Household_Type__c = 'Unknown/Not Reported';
		sh.C501_Phone__c = 'Phone';
		sh.C501_Other_Phone__c = 'OtherPhone';
		sh.C501_Years_At_Current_Address__c = 5;
		sh.C501_Current_Address_Move_In_Year__c = date.today();

		update sh;

		// Check trigger replication from C501_Service_Household__c to Account
		Account hh_update = [select ShippingStreet from Account where id =: hh.id];
		System.assertEquals(hh_update.ShippingStreet, sh.C501_ShippingStreet__c);

		C501_Service_Contact__c sc = new C501_Service_Contact__c(
			Name = 'C501_Service_Contact__c.Name',
			C501_Contact_Id__c = c.C501_Contact_Id__c,
			C501_Service_Id__c = hh.C501_Service_Id__c,
			C501_Service_Household_Id__c = sh.Id,
			C501_Contact__c = c.Id,
			C501_Last_Name__c = 'C501_Service_Contact__c.C501_Last_Name__c'
		);
		insert sc;

		// Call update to execute trigger
		sc.C501_Last_Name__c = 'C501_Service_Contact__c.C501_Last_Name__c';
		sc.C501_Nickname__c = 'C501_Service_Contact__c.C501_Nickname__c';
		sc.C501_First_Name__c = 'C501_Service_Contact__c.C501_First_Name__c';
		sc.C501_FirstName_Initial__c = 'C';
		sc.C501_Last_Name_Other__c = 'C501_Service_Contact__c.C501_Last_Name_Other__c';
		sc.C501_Last_Name__c = 'C501_Service_Contact__c.C501_Last_Name__c';
		sc.C501_Middle_Name__c = 'C501_Middle_Name__c';
		sc.C501_Birthdate__c = date.today();
		sc.C501_Partial_Social_Security_Id__c = 'xxx-xx-xxxx';
		sc.C501_Primary_Contact__c = true;
		sc.C501_Age__c = 10;
		sc.C501_Military_Status__c = 'Unknown/Not Reported';
		sc.C501_Disabling_Condition_Special_Needs__c = 'Unknown/Not Reported';
		sc.C501_Education_Level__c = 'Unknown/Not Reported';
		sc.C501_Health_Insurance__c = 'Unknown/Not Reported';
		sc.C501_Race__c = 'Unknown/Not Reported';
		sc.C501_Ethnicity__c = 'Unknown/Not Reported';
		sc.C501_Gender__c = 'Unknown/Not Reported';

		update sc;

		// Check trigger replication from C501_Service_Contact__c to Contact
		Contact c_update = [select LastName, FirstName from Contact where id =: c.id];
		System.assertEquals(c_update.LastName, sc.C501_Last_Name_Other__c);
		System.assertEquals(c_update.FirstName, sc.C501_Nickname__c);
	}
}